namespace MSFSSHTTP.Services.SubRequestHandlers
{
    /// <summary>
    /// Shared context passed to all sub-request handlers during processing of a single Request.
    /// Allows handlers to share state (e.g., SchemaLockId set by Coauth, consumed by GetDocMetaInfo).
    /// </summary>
    public class SubRequestContext
    {
        public string FilePath { get; }
        public string WebRootPath { get; }

        private FileInfo _fileInfo;
        public FileInfo FileInfo => _fileInfo ??= new FileInfo(FilePath);

        /// <summary>
        /// Schema lock ID set by the Coauth handler, consumed by GetDocMetaInfo handler.
        /// </summary>
        public string SchemaLockId { get; set; }

        /// <summary>
        /// Binary payload generated by the Cell handler for QueryChanges responses.
        /// </summary>
        public byte[] BinaryPayload { get; set; }

        public SubRequestContext(string filePath, string webRootPath)
        {
            FilePath = filePath;
            WebRootPath = webRootPath;
        }
    }
}
